server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
  shutdown: graceful

spring:
  datasource:
    hikari:
      schema: migrations
    url: jdbc:postgresql://localhost:5432/bayztrackerdb

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    schemas: migrations
    locations: classpath:db/migration

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    org:
      springframework: error

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    version: 3.0
